### ISSUE TITLE
Hyperlinks are not rendered nor the control going into onHyperlink.

### ISSUE THREAD

**Issue by vikkrantxx7** [tbluemel/rtf.js#70]
Text containing hyperlinks is not rendered.

**Comment by zoehneto** [comment]
I just pushed a new release to npm containing the fix from issue #60. If that isn't your issue please provide a sample file demonstrating the issue.

**Comment by vikkrantxx7** [comment]
It is still not fixed. Try rendering the attached file.

[word pad pic link.zip](https://github.com/tbluemel/rtf.js/files/5568503/word.pad.pic.link.zip)

**Comment by zoehneto** [comment]
There was a bug in the latest version which prevented your sample from running at all (due to infinite recursion). I have published a bugfix for that. Afterwards I get the following result (left libreoffice, right our sample page):
![image](https://user-images.githubusercontent.com/8282547/99819534-e0de2e00-2b4f-11eb-9c7e-348d794aec57.png)
This looks correct to me (apart from the table, which we don't support).

**Comment by vikkrantxx7** [comment]
This is now fixed. Appreciate the efforts :+1:
