### ISSUE TITLE
State handling

### ISSUE THREAD

**Issue by zoehneto** [tbluemel/rtf.js#8]
While the state is handled correctly during parsing using `pushState` and `popState`, this data is not used for the `buildDom` function. This leads to properties which are applied within a paragraph but never removed when `popState` is called.

Consider the following example: `{\rtf1\ansi\ansicpg1252
{Some Text }{\i italic text}{ text which shouldn't be italic}
}`

During parsing the `\i` keyword is applied, but when calling `popState` at the curly bracket it is not removed so the rest of the text is also italic.

**Comment by tbluemel** [comment]
I think there are also some more fundamental issues, e.g. how \par is handled.  I have started work on adding support for tables and at least the \par issue is causing some major problems, resulting in me having to re-architect quite a bit.  This issue might actually be fixed in my branch, but I haven't verified.

**Comment by tbluemel** [comment]
I pushed my table-support branch, but note that it has lots of issues and doesn't quite work yet.

**Comment by zoehneto** [comment]
I just tested your branch, the issue still exists in the current version.

**Comment by zoehneto** [comment]
`popState` needs to update the chp used by `buildDom`.
